import Head from 'next/head'
import ProductCart from '../components/product cart'
import ArrowSVG from '../components/SVG/ArrowSVG'
import AdvertCartItem from '../components/advert cart'
import { useAllProducts } from '../hook'
import { useEffect } from 'react'

interface product {
  id:number
  category:string
  description:string
  image:string
  price:number
  title:string
  rating:object
}

export default function Home() {
  const { data: product, isLoading } = useAllProducts()

  if(isLoading){
    return <img src="/image/loading.gif" />
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main>
        <div className='product-container'>
        <div className="cart cart-advert">
          <h2>
              Всё для комфортной работы
          </h2>
          <ArrowSVG/>
          <AdvertCartItem
            image='/image/allinone.png'
            discount='25%'
            text='на товары для кабинета'
            bigimage={false}
            ltr={true}
            theme={"dark"}
          />

          <AdvertCartItem
            image='/image/allinone.png'
            discount='25%'
            text='на товары для кабинета'
            bigimage={true}
            ltr={false}
            theme={"light"}
          />

        </div>

          {product.map((value:product,index:number)=>{
            return <ProductCart 
                      key={index}
                      image={value.image}
                      title={value.title}
                      id={value.id}
                      price={value.price}
                      description={value.description}
                      rating={value.rating}
                      category={value.category}
                   />
          })}
          
        </div>
      </main>
    </>
  )
}
